### ISSUE TITLE
[suggestion] Allow to add new labels to the node

### ISSUE THREAD

**Issue by cmoulliard** [dajudge/kindcontainer#363]
## Suggestion

The kind go project allows to set additonal labels to a node using the type field
```
// https://github.com/kubernetes-sigs/kind/blob/296749aa2de8577f6865e4db1870d2566a28d14b/pkg/apis/config/v1alpha4/types.go#L108

// Labels are the labels with which the respective node will be labeled
Labels map[string]string `yaml:"labels,omitempty" json:"labels,omitempty"`
```
that a user can define par of the kube config file
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: "kindest/node:v1.31.4"
  labels:
    ingress-ready: "true"
  extraPortMappings:
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
...
```
that the kind go project will render in the template using the field
```
// https://github.com/kubernetes-sigs/kind/blob/f96632a3c84686f5cf322e1d5f0201b02ca324e9/pkg/cluster/internal/kubeadm/config.go#L243-L248
  kubeletExtraArgs:
    node-ip: "{{ .NodeAddress }}"
    provider-id: "kind://{{.NodeProvider}}/{{.ClusterName}}/{{.NodeName}}"
    node-labels: "{{ .NodeLabels }}"
```

Such a feature is not supported by this project and is blocking by example the deployment of the ingress controller where a new label has been declared part of the `nodeSelector` section
```
// https://github.com/kubernetes/ingress-nginx/blob/main/deploy/static/provider/kind/deploy.yaml#L508
 nodeSelector:
    ingress-ready: "true"
    kubernetes.io/os: linux
```

**Comment by dajudge** [comment]
Hi @cmoulliard! Thank you for your input!

Would maybe something a long these lines solve the problem you describe?

https://github.com/dajudge/kindcontainer/blob/cc646b8b01f23a74cc9c6796bf3c4eaa1a1b7c26/src/test/java/com/dajudge/kindcontainer/kubectl/KubectlLabelFluentTest.java#L38

**Comment by cmoulliard** [comment]
Some changes are required within the existing code:
- Add a new field to allow a user to pass using a property the labels to be added the the Node
- Update the `kubeadm-1.[21,24].0.yaml` files to allow to pass the labels part of the following field
```
  kubeletExtraArgs:
    fail-swap-on: "false"
    node-ip: {{ .NodeIp }}
    node-labels: {{ .NodeLabels }}
    provider-id: kind://docker/kind/kindcontainer-control-plane
```
- Add labels to the list of the params
```
// https://github.com/dajudge/kindcontainer/blob/f89039b84c56ffffbd9deb0d3d05a5a3022c1d51/src/main/java/com/dajudge/kindcontainer/KindContainer.java#L206

        final Map<String, String> params = new HashMap<String, String>() {{
            put(".NodeIp", containerInternalIpAddress);
            put(".NodeLabels", nodeLabels);
..
```
**Note**: We will have also to adapt this method which until now only accept a Map<String, String> and only a key and value and not a list a values = labels !!
```
//     private static String template(String string, final Map<String, String> replacements) {
        return replacements.entrySet().stream()
                .map(r -> ((Function<String, String>) (s -> s.replace("{{ " + r.getKey() + " }}", r.getValue()))))
                .reduce(Function.identity(), Function::andThen)
                .apply(string);
    }
```
